### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by thuyxd** [thuyxd/Booking-Room#1]

**Comment by thuyxd** [comment]
Mọi người xem lại phần README.sd xem có cần sửa thêm gì nữa không nhé.

**Comment by thuyxd** [comment]
Chốt lại phần Readme luôn nhé!

**Comment by thuyxd** [comment]
[Hoàn thành README.sd](https://github.com/thuyxd/Booking-Room/blob/master/README.md)

**Comment by thutra050398** [comment]
ok rồi nhé

**Comment by kullov** [comment]
ok, Nga update hình ảnh demo trang chủ nhé, phần body sẽ update sau [Demo trang chủ](https://github.com/thuyxd/Booking-Room/wiki/M%E1%BB%99t-s%E1%BB%91-giao-di%E1%BB%87n-ch%C3%ADnh-c%E1%BB%A7a-website)

**Comment by thuyxd** [comment]
Ựa, đây là phần Readme, giao diện chỗ này mà [Giaodien](https://github.com/thuyxd/Booking-Room/issues/2)

**Comment by kullov** [comment]
Phần readme hoàn thành r nhá
