### ISSUE TITLE
Xây dựng phần chức năng

### ISSUE THREAD

**Issue by kullov** [thuyxd/Booking-Room#12]

**Comment by thutra050398** [comment]
Phần này tiến hành thế nào vậy mn?

**Comment by kullov** [comment]
Phần này mình sẽ xây dựng controller, service, repository... nhé! Trà ơi bà tìm hiểu phần unit Test nhé!

**Comment by thuyxd** [comment]
Phần lấy ra sự phụ thuộc của các tỉnh thành phố t vẫn đang làm nhé, t vừa push phần t đang làm nhưng chưa xong, t sẽ cố gắng hoàn thành sớm.

**Comment by kullov** [comment]
Ok nhé

**Comment by kullov** [comment]
Phần chức năng xong r nhé mn!
