### ISSUE TITLE
Hoàn thành giao diện web

### ISSUE THREAD

**Issue by kullov** [thuyxd/Booking-Room#2]

**Comment by thuyxd** [comment]
T sẽ lm giao diện phần đăng tin cho thuê phòng trọ của người cho thuê
Nga làm giao diện phần đăng kí, đăng nhập.
Trà làm phần giao diện đăng kí thông tin của khách vãng lai.
Mọi ng cố gắng làm cho hiệu quả nhé ! :)

**Comment by kullov** [comment]
T update phần giao diện đăng nhập r nhé! [login](https://github.com/thuyxd/Booking-Room/commit/ed8d8b192b19e80c9d1e9abbf9dce0291bab0443)

**Comment by kullov** [comment]
Thủy cmt nốt giao diện của phần postNews vào wiki nhé!

**Comment by kullov** [comment]
T vừa sửa lại giao diện tìm kiếm, mn vào xem nhé!

**Comment by kullov** [comment]
T vừa update lại giao diện chính nhé! (vẫn đang hoàn thiện) [giao diện](https://github.com/thuyxd/Booking-Room/wiki/M%E1%BB%99t-s%E1%BB%91-giao-di%E1%BB%87n-ch%C3%ADnh-c%E1%BB%A7a-website)

**Comment by thuyxd** [comment]
giao diện chính nt có đơn giản quá k nga, có thể cho thêm quảng cáo hay tin khuyến mãi gì đấy nhìn cho đẹp hơn đc k m

**Comment by kullov** [comment]
Chưa xong đâu, t ms làm phần tin nổi bật thôi, còn nữa mà

**Comment by thuyxd** [comment]
ok ok

**Comment by kullov** [comment]
T vừa update lại [giao diện chính](https://github.com/thuyxd/Booking-Room/wiki/M%E1%BB%99t-s%E1%BB%91-giao-di%E1%BB%87n-ch%C3%ADnh-c%E1%BB%A7a-website) nhé! Mn vào xem tnao nhé! Thủy update nốt giao diện hiển thị bài đăng trong tối nay nhé!

**Comment by thutra050398** [comment]
tôi thấy ok đẹp rồi đó

**Comment by thuyxd** [comment]
t update giao diện xem tin + trang giới thiệu rồi đấy, mọi ng xem cho ý kiến nhé

**Comment by kullov** [comment]
Phần giao diện là đã hoàn thành rồi nhé!
