### ISSUE TITLE
Xây dựng CSDL

### ISSUE THREAD

**Issue by kullov** [thuyxd/Booking-Room#5]
Phần CSDL sẽ do Trà hoàn thiện!

**Comment by thutra050398** [comment]
ok các bạn

**Comment by thutra050398** [comment]
mọi người xem và chỉnh sửa giúp t xem db này đã ổn chưa?
![image](https://user-images.githubusercontent.com/44607842/48970030-ac573a80-f039-11e8-80dd-6b0c851bd6c9.png)

**Comment by kullov** [comment]
Trà update lại bảng CSDL mới nhé!

**Comment by thutra050398** [comment]
Mọi người vào link này để cập nhật chức năng và test database nhé
 [](https://docs.google.com/spreadsheets/d/1S4ZOT8edOcK_sZVXPSniQrXh4GrXimDKCJy2m8yzBCI/edit?usp=sharing)

**Comment by thutra050398** [comment]
![booking_room](https://user-images.githubusercontent.com/44607842/49296407-bf12b900-f4ea-11e8-93d5-976574a0e154.png)

**Comment by thutra050398** [comment]
Mn import cái này vào xem ok k nhé?
[booking_room.zip](https://github.com/thuyxd/Booking-Room/files/2633811/booking_room.zip)

**Comment by kullov** [comment]
OK Trà nha! T thấy ổn r đấy

**Comment by kullov** [comment]
CSDL hiện tại ok r, bh tập trung phần chức năng và unitTest nhé mn!
